version: '3.8'

services:
  db:
    container_name: mysql-spring-boot
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes       # ✅ allows root with no password
      - MYSQL_DATABASE=springdocker
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  app:
    container_name: springboot-app
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springdocker
    depends_on:
      - db
    restart: always



volumes:
  mysql-data:
