name: CICD
on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t sushil2044/springboot-example:latest .
      - name: Publish image to docker hub
        run: docker push sushil2044/springboot-example:latest

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64,aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Run MySQL Container (No Password)
        run: |
          docker rm -f mysql-container || true
          docker run -d \
            --name mysql-container \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
            -e MYSQL_DATABASE=springdocker \
            -p 3306:3306 \
            mysql:8.0
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          sleep 20
          docker exec mysql-container mysql -uroot -e "CREATE USER IF NOT EXISTS 'springuser'@'%' IDENTIFIED BY '';"
          docker exec mysql-container mysql -uroot -e "GRANT ALL PRIVILEGES ON springdocker.* TO 'springuser'@'%';"
          docker exec mysql-container mysql -uroot -e "FLUSH PRIVILEGES;"
      - name: Pull Image from docker hub
        run: docker pull sushil2044/springboot-example:latest
      - name: Delete old container
        run: docker rm -f springboot-example-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container sushil2044/springboot-example:latest


